server:
  port: 8081
  servlet:
    context-path: "/api/v1"

spring:
  application:
    name: rock-paper-scissors
  datasource:
    url: jdbc:postgresql://localhost:5432/game?currentSchema=game
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000

  # JPA Config
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      use_sql_comments: true
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: game

  # Flyway Config
  flyway:
    enabled: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration